name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Set up Firebase Authentication
        env:
          FIREBASE_SERVICE_ACCOUNT_TINA_MARTINS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TINA_MARTINS }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT_TINA_MARTINS" > firebase-service-account.json

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT_TINA_MARTINS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TINA_MARTINS }}
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json